### ISSUE TITLE
need better config file validation

### ISSUE THREAD

**Issue by matthigger** [matthigger/gradescope_mean#19]
invalid values throw error in main code, can be challenging for others to debug how their config file is formatted improperly.

For example:

waive: 
  test.a@northeastern.edu: 

the list of assignments to be waived is empty ... causes an error as we try to split on comma.  tough for new user to see what happened.

**Comment by matthigger** [comment]
the null values:

```
  assignments:
    exclude_complete_thresh: null
    exclude: null
    substitute: null
```

don't work properly, they're read in as floats
